### ISSUE TITLE
How to predict one image?

### ISSUE THREAD

**Issue by MinhThanghus** [Jorwnpay/TGRS_BETL#1]
Hi @Jorwnpay 
I want predict one image with results training model. But i tried many ways to no avail.
Can You tell me?
thanks you

**Comment by Jorwnpay** [comment]
Hi @MinhThanghus
You pointed out a good question.  You can train the BETL model and save its weights first, then write an inference code, and load the weights you saved. In the end, you should input your test image into the model to get a prediction.
This repo doesn't implement this function yet.

**Comment by MinhThanghus** [comment]
@Jorwnpay  
Thank for your reply!

**Comment by MinhThanghus** [comment]
have solutions
